source 'https://rubygems.org'

gem 'minitest-reporters'
gem 'minitest', '5.10.3'
gem 'test-unit', :require => false
gem 'rspec', '>= 3.4.0', '< 3.6.0'
gem 'pry-byebug'

unless ENV["CI"]
  gem 'gorgon', :path => "~/src/Gorgon"
end
